exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

predfpath: ../cosc426/labs/lab02/predictions/predictions.tsv

datafpath: ../cosc426/labs/lab02/data/data.tsv

resultsfpath: ../cosc426/labs/lab02/results/resutls.tsv

save: by_pair, by_cond
